### ISSUE TITLE
Manually produce a published artifact

### ISSUE THREAD

**Issue by brianraymor** [HumanCellAtlas/dcp-prototype#27]
[Artifact Specification](https://docs.google.com/document/d/1WglovQ5rBnIS2aBKmnd4oolC3tX9Z4A8FPBXNpH7lZY/edit)

**Comment by parthshahva** [comment]
I have passed a workable artifact to @calvin to load into the browser backend. However mentioning the following:
1) I encountered some issues with entities in the first project load. I will need to work with @arathi.mani next week to sort these out. For the time being, some of the values in the artifact are hardcoded while we work through this.
2) The values available in the artifact are going to dramatically change this week. @jahilton's schema changes brings in a lot of new properties to the various entities which will need to be accounted for. We will first need to update the db schema and the migration tool. I will work with Calvin when instituting this change.
3) I will also be changing the file format of the artifacts. After doing some thinking today about entity structures and artifact versioning, I’ve realized that we need a more detailed artifact spec for client consumption. This week, I will be publishing v1 of a jsonschema representing the artifact spec rather than the current collection of tsvs. This will allow us to manage changes to the artifact spec as code in GitHub and will allow for better structured data to be passed to the clients. cc @ambrose @marcus @calvin for comment
4) Per a discussion with @ambrose and @marcuskinsella, we are retaining ontology values rather than labels in the artifact. The data browser browser will need to do ols lookups while storing the data to retain human readable labels (fyi @calvin)
5) The artifact is currently pointing to the s3 uris directly in the ledger bucket. This is okay since we will only be maintaining one artifact in this prototyping phase. Very soon we will move to copying the files over to a separate artifact bucket so that the files are immutable per artifact version.

**Comment by ambrosejcarr** [comment]
Nice. Thanks for getting this done so efficiently!

Spec in jsonschema feels like a good step.

It might be a good idea to make a small sphinx or Jinja based document that
parses the schema into something more readable. As a user facing object,
the artifact will need to be documented.
